I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/prologue.rpy", line 6, in script
    with dissolve
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/prologue.rpy", line 6, in script
    with dissolve
  File "C:\Users\RENNKA\Desktop\renpy-7.3.5-sdk\renpy\execution.py", line 59, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
rks 1.0
Wed Dec 11 18:41:47 2019
